//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WichtelApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WichtelApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ingo {
            get {
                object obj = ResourceManager.GetObject("Ingo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jan {
            get {
                object obj = ResourceManager.GetObject("Jan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Jannik {
            get {
                object obj = ResourceManager.GetObject("Jannik", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kara {
            get {
                object obj = ResourceManager.GetObject("Kara", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Leon {
            get {
                object obj = ResourceManager.GetObject("Leon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lukas {
            get {
                object obj = ResourceManager.GetObject("Lukas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Moritz {
            get {
                object obj = ResourceManager.GetObject("Moritz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Robin {
            get {
                object obj = ResourceManager.GetObject("Robin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In den dichten Wäldern Polens, dort, wo die Bäume so alt und groß wie Riesen sind und die Flüsse dunkel und tief fließen, lebte der legendäre Biber Bober Willokoschinski. Man nannte ihn „Bober Wielki,” den „Großen Biber,” denn seine Baukünste waren in der ganzen Region berüchtigt. In einem versteckten Flusslauf baute Willo seine Dämme, die so stark und gewaltig waren, dass selbst die mächtigsten Schiffe an ihnen scheiterten und die Wasserstraße blockierten. &lt;br&gt;
        ///    &lt;br&gt; Bober Willokoschinski war kein gewöh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Story_Ingo {
            get {
                return ResourceManager.GetString("Story_Ingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan war bekannt als der ärmste Student nördlich des Äquators – ein Mann ohne finanziellen Spielraum, aber mit einem Herzen, das für Festivals und Konzerte schlug. In seiner kleinen Ein-Zimmer-Wohnung stapelten sich unzählige Pflanzen, von denen einige längst die Fensterbank erobert hatten und in einer Art wilder Dschungelgemeinschaft lebten. Trotz seiner begrenzten Mittel gab Jan das wenige, was er hatte, lieber für Konzerttickets und gelegentliche Mitbringsel für seine Pflanzensammlung aus. &lt;br&gt;
        ///    &lt;br&gt; N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Story_Jan {
            get {
                return ResourceManager.GetString("Story_Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jannich, ein Mönch mit beeindruckenden Muskelbergen, wuchs in einem abgelegenen Kloster in Hoogstede auf. Das Kloster war so extrem abgelegen, dass es in einem Umkreis von 100 Kilometern nur das Kloster und ein einzelnes Fitnessstudio gab. Bereits im zarten Alter von vier Jahren begann Jannich mit dem Kraftsport, da es im Kloster kaum andere Beschäftigungen gab. Um seine Muskeln aufzubauen, setzte er auf einen besonderen Joghurt, den er nach einem geheimen Familienrezept selbst herstellte. Dieser Jogurt war [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Story_Jannik {
            get {
                return ResourceManager.GetString("Story_Jannik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Kara, ne? Die is’ echt ’ne waschechte Norddeutsche, von noch nördlicher als Hamburg – also, dat is’ nich’ ohne! Dat Mädel hat ’ne Kindheit gehabt, die kannste nur im echten Norden haben. Jeden Tag in Gummistiefeln rumlatschen, auch wenn die Sonne scheint. Wattwanderungen bei Ebbe mit Opa, Krabben pulen zum Mittag, und dann jeden Sonntag, jawoll, bei Matschwetter ab inne Kirche mit den dicken Pullovern an. Als Kind hat sie sogar gelernt, das Rethwischer Alphabet zu gebärden, ne heilige, uralte Zeichenspr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Story_Kara {
            get {
                return ResourceManager.GetString("Story_Kara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In den Bergen Mexikos, wo die Nächte kühl und die Dämmerung golden schimmerte, lebte der legendäre Senor Leon. Man nannte ihn &quot;El Maestro de los Metales,&quot; denn sein Ruf als Meister der Metallarbeiten war weit über die Dörfer hinaus bekannt. In einem kleinen, unscheinbaren Dorf, das von riesigen Kakteen und verwunschenen Agaven umgeben war, führte Senor Leon eine kleine Schmiede, in der er Wunderwerke aus Metall schuf. &lt;br&gt;
        ///    &lt;br&gt; Es hieß, dass Senor Leon das Metall nicht nur schmiedete, sondern mit einer  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Story_Leon {
            get {
                return ResourceManager.GetString("Story_Leon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In einem abgelegenen Tal, verborgen zwischen dunklen Wäldern und nebelverhangenen Hügeln, lebte ein junger Mann namens Lukas. Obwohl Lukas ungewöhnlich groß war, fast so hoch wie die Bäume, war er schmal und schmächtig, mit feinen Händen, die ihn oft im Stich ließen. Seit seiner Kindheit litt er an einer chronischen Sehnenscheidenentzündung, die ihm selbst die einfachsten Bewegungen schmerzhaft erschwerte. Doch Lukas trug einen eisernen Willen in sich: Er wollte den sagenumwobenen Pfad zum Exil beschreiten  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Story_Lukas {
            get {
                return ResourceManager.GetString("Story_Lukas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortimer wuchs als Waisenkind in einer kleinen Stadt auf, in der die Legenden vom berüchtigten Drucker Print Eastwood kursierten. Eastwood, der gefürchtete Meister der Druckkunst, hatte Mortimers Eltern in einer blutigen Tintenexplosion getötet, als Mortimer noch ein kleiner Junge war. Seit diesem Tag brodelte ein unstillbarer Hass in ihm – Hass auf Drucker und alles, was sie in diese Welt brachten. &lt;br&gt;
        ///    &lt;br&gt; Mit 18 Jahren machte sich Mortimer auf, um Rache zu nehmen. Mit nichts als Entschlossenheit und [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Story_Moritz {
            get {
                return ResourceManager.GetString("Story_Moritz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robin war in der Grafschaft Shitdorf als der verrückteste Wissenschaftler weit und breit bekannt. Mit ungebändigtem Forscherdrang führte er regelmäßig Experimente an den Tauben der Gegend durch, was von den Anwohnern entweder belächelt oder beargwöhnt wurde. Er ließ die Vögel winzige Helme tragen, fütterte sie mit seltsamen Pulvern und setzte sie speziellen Lichtexperimenten aus – alles in der Hoffnung, die Grenzen des Taubenverstandes zu erweitern. Doch eines Tages, als er gerade tief in seine Lieblingsser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Story_Robin {
            get {
                return ResourceManager.GetString("Story_Robin", resourceCulture);
            }
        }
    }
}
